name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine notes path
        id: notes
        run: |
          TAG="${GITHUB_REF_NAME}"
          FILE="release-notes/${TAG}.md"
          if [ -f "$FILE" ]; then
            echo "path=$FILE" >> $GITHUB_OUTPUT
          else
            echo "path=" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body_path: ${{ steps.notes.outputs.path }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
